server {
    listen 80;
    
    # Root directory where the static files are stored
    root /usr/share/nginx/html;
    index index.html;

    # Handle client-side routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}
