"""Add invite_code to organizations

Revision ID: 26a3bb194065
Revises: e330768e083b
Create Date: 2026-06-20 23:56:50.972672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a3bb194065'
down_revision: Union[str, Sequence[str], None] = 'e330768e083b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_organizations_invite_code'), ['invite_code'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_invite_code'))
        batch_op.drop_column('invite_code')

    # ### end Alembic commands ###
