"""add interview scheduling

Revision ID: 4c59745c9898
Revises: e2a5ea6ac4ca
Create Date: 2026-06-15 01:02:41.309999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c59745c9898'
down_revision: Union[str, Sequence[str], None] = 'e2a5ea6ac4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meet_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('meet_link')

    # ### end Alembic commands ###
