"""add website_url

Revision ID: 583f8049d69c
Revises: b704f28bb79c
Create Date: 2026-06-19 02:01:05.439985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583f8049d69c'
down_revision: Union[str, Sequence[str], None] = 'b704f28bb79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_pages', schema=None) as batch_op:
        batch_op.drop_column('website_url')

    # ### end Alembic commands ###
