"""Add job_category to Job

Revision ID: 5d4970627628
Revises: cc69832557b9
Create Date: 2026-06-19 17:54:21.887709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4970627628'
down_revision: Union[str, Sequence[str], None] = 'cc69832557b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_category', sa.String(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('draft', 'open', 'closed', 'deleted', name='jobstatus', native_enum=False),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('draft', 'open', 'closed', 'deleted', name='jobstatus', native_enum=False),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
        batch_op.drop_column('job_category')

    # ### end Alembic commands ###
