"""Add logo and website to Organization

Revision ID: 769ca241c230
Revises: a8ecfee46807
Create Date: 2026-06-20 02:00:24.886272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769ca241c230'
down_revision: Union[str, Sequence[str], None] = 'a8ecfee46807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('website_url')
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
