"""Add CareerPage model

Revision ID: b704f28bb79c
Revises: ea700e27bcea
Create Date: 2026-06-19 00:22:44.225403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b704f28bb79c'
down_revision: Union[str, Sequence[str], None] = 'ea700e27bcea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    with op.batch_alter_table('career_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_pages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_career_pages_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_pages_slug'))
        batch_op.drop_index(batch_op.f('ix_career_pages_id'))

    op.drop_table('career_pages')
    # ### end Alembic commands ###
