"""add scorecard and offer letter

Revision ID: ee9d09fcada4
Revises: 583f8049d69c
Create Date: 2026-06-19 14:01:25.903509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9d09fcada4'
down_revision: Union[str, Sequence[str], None] = '583f8049d69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_scorecards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_name', sa.String(), nullable=False),
    sa.Column('communication_score', sa.Integer(), nullable=False),
    sa.Column('technical_score', sa.Integer(), nullable=False),
    sa.Column('culture_score', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_scorecards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_scorecards_id'), ['id'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_letter_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('offer_letter_url')

    with op.batch_alter_table('interview_scorecards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_scorecards_id'))

    op.drop_table('interview_scorecards')
    # ### end Alembic commands ###
